// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3SvzTbWtGW_bp8qame7jE5mrGEC5SewQ',
    appId: '1:144407449241:web:f8046a6db26f94cdf8f208',
    messagingSenderId: '144407449241',
    projectId: 'aquiles-f09a3',
    authDomain: 'aquiles-f09a3.firebaseapp.com',
    storageBucket: 'aquiles-f09a3.firebasestorage.app',
    measurementId: 'G-MCZKRBTZ4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-oopnvMoxRZTbeyUp_x8rACngivf1Rs',
    appId: '1:144407449241:android:6183815b8fc03865f8f208',
    messagingSenderId: '144407449241',
    projectId: 'aquiles-f09a3',
    storageBucket: 'aquiles-f09a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7wCrjDel3eWpQ3dWerFPQSdTDa9KsQJk',
    appId: '1:144407449241:ios:ba2f0846369d7ef3f8f208',
    messagingSenderId: '144407449241',
    projectId: 'aquiles-f09a3',
    storageBucket: 'aquiles-f09a3.firebasestorage.app',
    iosBundleId: 'com.example.aquiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7wCrjDel3eWpQ3dWerFPQSdTDa9KsQJk',
    appId: '1:144407449241:ios:ba2f0846369d7ef3f8f208',
    messagingSenderId: '144407449241',
    projectId: 'aquiles-f09a3',
    storageBucket: 'aquiles-f09a3.firebasestorage.app',
    iosBundleId: 'com.example.aquiles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3SvzTbWtGW_bp8qame7jE5mrGEC5SewQ',
    appId: '1:144407449241:web:59057c41c22166ecf8f208',
    messagingSenderId: '144407449241',
    projectId: 'aquiles-f09a3',
    authDomain: 'aquiles-f09a3.firebaseapp.com',
    storageBucket: 'aquiles-f09a3.firebasestorage.app',
    measurementId: 'G-9GMFM6VVK2',
  );

}